# Generated by Django 6.0.7 on 2026-07-29 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_score',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basis.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basis.student')),
            ],
        ),
    ]
