# Generated by Django 6.1 on 2026-08-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0003_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Unbekannt', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='unbekannt', max_length=50),
            preserve_default=False,
        ),
    ]
