# Generated by Django 6.1 on 2026-08-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0004_remove_student_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Studenten-ID'),
        ),
    ]
