# Generated by Django 6.1 on 2026-08-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0005_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
